alert("Welcome to our website!")
alert("Error! Please enter a valid password.")
alert("Welcome to JS land...\nHappy Coding!")
alert("Welcome to JS land...")
alert("Happy Coding!\nPrevent this page from the creating additional diaologues. ")
alert("Hello...I can run javascript through my web browser's console.")
alert("Script in the head section")
alert("Script before the html content")
alert("Script inside the html content")
alert("Script after the html content")